# Usa una imagen base de Node.js
FROM node:20-alpine




# Crea el directorio de trabajo
WORKDIR /usr/src/app




# Copia package.json y package-lock.json (o yarn.lock) primero para aprovechar el cache de Docker
COPY backend/package*.json ./




# Instala las dependencias de producción
RUN npm install --production



# Copia el resto del código de la aplicación
COPY backend/. .

# Crea la carpeta uploads para Multer
RUN mkdir -p /usr/src/app/uploads


# Expone el puerto en el que corre tu backend
EXPOSE 4000



# Comando para iniciar la aplicación
CMD [ "node", "server.js" ]



